version: '3.5'

services:
  notificationapi:
    container_name: notificationapi
    image: wfigueiredo/notificationapi:latest
    env_file:
     - notificationapi.env
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
     - "5001:80"
     
  postgres:
    container_name: c_postgres
    image: postgres
    environment:
      - POSTGRES_DB=notificationapi
      - POSTGRES_USER=notificationapi
      - POSTGRES_PASSWORD=notificationapi
      - TZ='GMT-3'
      - PGTZ='GMT-3'
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
    
  rabbitmq:
    image: rabbitmq:3.7.5-management
    hostname: api-rabbitmq
    ports:
        - 5672:5672
        - 15672:15672
    #volumes:
    #    - ./data/rabbitmq:/var/lib/rabbitmq/mnesia/rabbit@app-rabbitmq:cached
    environment:
        RABBITMQ_ERLANG_COOKIE: 6085e2412b6fa88647466c6a81c0cea0
        RABBITMQ_DEFAULT_USER: radmin
        RABBITMQ_DEFAULT_PASS: radmin
 
       
networks:
  postgres:
    driver: bridge

volumes:
    postgres: