SET search_path TO NOTIFICATIONAPI;

DROP TABLE IF EXISTS NOTIFICATIONAPI.MESSAGE;

CREATE TABLE MESSAGE
(
	ID SERIAL 						NOT null,
	UNIQUEID 	varchar(40)			NOT null,
	GROUPID 	varchar(20)			NOT null,
	SOURCE		varchar(20)			NOT null,
	CONTENT		varchar(200)		NOT null,
	CREATEDAT	timestamp(20)		NOT null,
	CONSTRAINT PK_TB_MESSAGE 		PRIMARY KEY (ID),
	CONSTRAINT UNIQUE_TB_MESSAGE  	UNIQUE (UNIQUEID)
);